In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
import pandas as pd

In [2]:
def min_max_normalize(lst):
    """
        Helper function for movielens dataset, not useful for discrete multi class clasification.

        Return:
        Normalized list x, in range [0, 1]
    """
    maximum = max(lst)
    minimum = min(lst)
    toreturn = []
    for i in range(len(lst)):
        toreturn.append((lst[i]- minimum)/ (maximum - minimum))
    return toreturn

In [3]:
def z_standardize(X_inp):
    """
        Z-score Standardization.
        Standardize the feature matrix, and store the standarize rule.

        Parameter:
        X_inp: Input feature matrix.

        Return:
        Standardized feature matrix.
    """
    
    toreturn = X_inp.copy()
    for i in range(X_inp.shape[1]):
        std = np.std(X_inp[:, i])               # ------ Find the standard deviation of the feature
        mean = np.mean(X_inp[:, i])             # ------ Find the mean value of the feature
        temp = (X_inp[:, i] - mean) / std
        
        """
        for j in np.array(X_inp[:, i]):
            
           
                #TODO: 1. implement the standardize function
            
        
            temp += []
        """
        toreturn[:, i] = temp
    return toreturn

In [4]:
def sigmoid(x):
    """ 
        Sigmoid Function

        Return:
        transformed x.
    """
    """    
        #TODO: 2. implement the sigmoid function
    """
    return 1 / (1 + np.exp(-x))

In [5]:
class Logistic_Regression():
    
    def __init__(self):
        """
            Some initializations, if neccesary
        """
        
        self.model_name = 'Logistic Regression'
    
    def fit(self, X_train, y_train):
        """
            Save the datasets in our model, and do normalization to y_train
            
            Parameter:
                X_train: Matrix or 2-D array. Input feature matrix.
                Y_train: Matrix or 2-D array. Input target value.
        """
        
        self.X = X_train
        self.y = y_train
        
        count = 0
        uni = np.unique(y_train)
        for y in y_train:
            if y == min(uni):
                self.y[count] = 0
            else:
                self.y[count] = 1
            count += 1        
        
        n, m = X_train.shape
        self.theta = np.zeros(m)
        self.b = 0
    
    def gradient(self, X_inp, y_inp, theta, b):
        """
            Calculate the grandient of Weight and Bias, given sigmoid_yhat, true label, and data

            Parameter:
                X_inp: Matrix or 2-D array. Input feature matrix.
                y_inp: Matrix or 2-D array. Input target value.
                theta: Matrix or 1-D array. Weight matrix.
                b: int. Bias.

            Return:
                grad_theta: gradient with respect to theta
                grad_b: gradient with respect to b

        NOTE: There are several ways of implementing the gradient. We are merely providing you one way
        of doing it. Feel free to change the code and implement the way you want.
        """
        grad_b = b
        grad_theta = np.zeros_like(theta)

        for (xi, yi) in zip(X_inp, y_inp):
            z = np.dot(theta, xi) + b
            sigmoid_yhat = sigmoid(z)
            grad_b += (sigmoid_yhat - yi)
            grad_theta += (sigmoid_yhat - yi) * xi
        
        grad_b /= len(X_inp)
        grad_theta /= len(X_inp)
    
        return grad_theta, grad_b

    def gradient_descent_logistic(self, alpha, num_pass, early_stop=0, standardized = True):
        """
            Logistic Regression with gradient descent method

            Parameter:
                alpha: (Hyper Parameter) Learning rate.
                num_pass: Number of iteration
                early_stop: (Hyper Parameter) Least improvement error allowed before stop. 
                            If improvement is less than the given value, then terminate the function and store the coefficents.
                            default = 0.
                standardized: bool, determine if we standardize the feature matrix.
                
            Return:
                self.theta: theta after training
                self.b: b after training
        """
        
        if standardized:
            self.X = z_standardize(self.X)
        
        n, m = self.X.shape

        for i in range(num_pass):    
            
            """
                TODO: 4. Modify the following code to implement gradient descent algorithm
            """
            grad_theta, grad_b = self.gradient(self.X, self.y, self.theta, self.b)
            temp_theta = self.theta - alpha * grad_theta
            temp_b = self.b - alpha * grad_b

            """
                TODO: 5. Modify the following code to implement early Stop Mechanism (use Logistic Loss when calculating error)
            """ 
            
            previous_y_hat = sigmoid(np.dot(self.X, self.theta) + self.b)
            temp_y_hat = sigmoid(np.dot(self.X, temp_theta) + temp_b)
            pre_error = - np.mean(self.y * np.log(previous_y_hat) + (1 - self.y) * np.log(1 - previous_y_hat))
            temp_error = - np.mean(self.y * np.log(temp_y_hat) + (1 - self.y) * np.log(1 - temp_y_hat))
            #print(f'temp err: {temp_error}')
            #print(f'pre err: {pre_error}')
            #print(f'ratio: {abs(abs(temp_error - pre_error) / pre_error)}')

            if (abs(temp_error - pre_error) < early_stop) | (abs(abs(temp_error - pre_error) / pre_error) < early_stop):
                print('early stop')
                return temp_theta, temp_b

            #pre_error = temp_error
            #previous_y_hat = temp_y_hat
            self.theta = temp_theta
            self.b = temp_b

        return self.theta, self.b

    
    def predict_ind(self, x: list):
        """
            Predict the most likely class label of one test instance based on its feature vector x.

            Parameter:
            x: Matrix, array or list. Input feature point.
            
            Return:
                p: prediction of given data point
        """
        
        """
            TODO: 7. Implement the prediction function
        """
        x = np.array(x)
        z = np.dot(self.theta, x) + self.b
        p = sigmoid(z)
        return p

    def predict(self, X):
        """
            X is a matrix or 2-D numpy array, represnting testing instances. 
            Each testing instance is a feature vector. 
            
            Parameter:
            x: Matrix, array or list. Input feature point.
            
            Return:
                p: prediction of given data matrix
        """
        
        """
            TODO: 8. Revise the following for-loop to call predict_ind to get predictions.
        """
        
        ret = []                  # -------- Use predict_ind to generate the prediction list
        for x in X:
            # call predict_ind to get prediction for each instance
            pred = self.predict_ind(x)
            ret.append(pred)
    
        return ret

In [6]:
url_Wine = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
#names = ['f_acid', 'v_acid', 'c_acid', 'sugar', 'chlorides', 'f_SO2', 't_SO2', 'density', 'ph', 'sulphates', 'alcohol', 'quality']
wine = pd.read_csv(url_Wine, delimiter=';')

In [7]:
wine5 = wine.loc[wine.quality == 5]
wine6 = wine.loc[wine.quality == 6]
wineall = pd.concat([wine5,wine6])
wineall

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
4               7.4              0.70         0.00             1.9      0.076   
5               7.4              0.66         0.00             1.8      0.075   
...             ...               ...          ...             ...        ...   
1592            6.3              0.51         0.13             2.3      0.076   
1593            6.8              0.62         0.08             1.9      0.068   
1595            5.9              0.55         0.10             2.2      0.062   
1596            6.3              0.51         0.13             2.3      0.076   
1598            6.0              0.31         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
4                    11.0                  34.0  0.99780  3.51       0.56   
5                    13.0                  40.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1592                 29.0                  40.0  0.99574  3.42       0.75   
1593                 28.0                  38.0  0.99651  3.42       0.82   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
4         9.4        5  
5         9.4        5  
...       ...      ...  
1592     11.0        6  
1593      9.5        6  
1595     11.2        6  
1596     11.0        6  
1598     11.0        6  

[1319 rows x 12 columns]

In [8]:
X = np.array(wineall.iloc[:,:10])
Y = np.array(wineall.quality)

In [9]:
count = 0
for y in Y:
    if y == 5:
        Y[count] = -1
    else:
        Y[count] = 1
    count += 1

In [10]:
logit = Logistic_Regression()
logit.fit(X, Y)

In [11]:
g = logit.gradient_descent_logistic(0.001, 20000)

In [12]:
w, b = g

In [13]:
g

(array([ 0.31900196, -0.37231203,  0.01426821,  0.19981285, -0.22381852,
         0.16420569, -0.59156683, -0.48309589,  0.19216084,  0.46322814]),
 -0.07960530546470693)

In [14]:
hat = np.array(w.dot(z_standardize(X).T) + b)

In [15]:
hat1 = sigmoid(hat)
hat1

array([0.33228718, 0.2322121 , 0.28437267, ..., 0.70643604, 0.67193117,
       0.71691831])

In [16]:
np.where(hat1 >= 0.5)

(array([  10,   15,   17,   18,   19,   24,   25,   26,   29,   30,   35,
          38,   45,   48,   49,   50,   52,   56,   57,   58,   61,   62,
          64,   72,   75,   83,   89,   94,  110,  112,  132,  143,  150,
         153,  156,  157,  158,  159,  160,  167,  178,  182,  183,  185,
         186,  189,  192,  218,  219,  220,  224,  226,  228,  229,  231,
         233,  234,  235,  239,  242,  252,  260,  263,  264,  277,  278,
         279,  283,  292,  305,  313,  317,  320,  329,  350,  352,  353,
         384,  386,  388,  394,  399,  400,  401,  402,  406,  407,  408,
         420,  421,  428,  430,  434,  437,  441,  442,  443,  444,  447,
         448,  449,  451,  452,  454,  455,  459,  461,  463,  464,  468,
         469,  471,  472,  477,  478,  479,  480,  485,  486,  491,  493,
         497,  500,  504,  506,  509,  514,  515,  518,  523,  525,  527,
         530,  531,  532,  536,  538,  539,  540,  543,  546,  555,  560,
         561,  562,  563,  564,  567, 

In [17]:
count = 0
for i in range(len(hat)):
    if hat1[i] < 0.5:
        if Y[i] == 0:
            count += 1
    else:
        if Y[i] == 1:
            count += 1
count

921

In [18]:
928/1319

0.7035633055344959